#made by shivam patel
from telethon import events

import asyncio

from wolf.utils import admin_cmd
from wolf import bot as wolfs
@wolfs.on(admin_cmd("hdd"))
async def _(event):
    if event.fwd_from:
        return
    animation_interval = 1
    animation_ttl = range(0,20)
    await event.edit("Happy Diwali Dosto🤗")
    animation_chars = [
            """-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙""",
            """💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜""",
            """"💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖 
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖""",
            """❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖 
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖 
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙""",
            """💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖 
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖 
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️""",
 """💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
---💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💜happy💜diwali💜
----💜happy💜diwali💜
---💜happy💜diwali💜
--💜happy💜diwali💜
-💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💜happy💜diwali💜
💜happy💜diwali💜
💜happy💜diwali💜
-💜happy💜diwali💜
--💜happy💜diwali💜
----💜happy💜diwali💜
-----💜happy💜diwali💜
-----💖happy💖diwali💖
-----💖happy💖diwali💖
-----💖happy💖diwali💖
----💖happy💖diwali💖
---💖happy💖diwali💖
--💖happy💖diwali💖
-💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖 
💖happy💖diwali💖
💖happy💖diwali💖
💖happy💖diwali💖
-💖happy💖diwali💖
--💖happy💖diwali💖
---💖happy💖diwali💖
----💖happy💖diwali💖 
---💙happy💙diwali💙
----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
-----💙happy💙diwali💙
----💙happy💙diwali💙
---💙happy💙diwali💙
--💙happy💙diwali💙
-💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
💙happy💙diwali💙
-💙happy💙diwali💙
--💙happy💙diwali💙
--♥️happy❤️diwali♥️
---❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
-----♥️happy❤️diwali♥️
-----❤️happy♥️diwali❤️
----♥️happy❤️diwali♥️
---♥️happy❤️diwali❤️
--♥️happy❤️diwali♥️
-♥️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
❤️happy♥️diwali❤️
❤️happy♥️diwali♥️
❤️happy♥️diwali♥️
-❤️happy♥️diwali♥️
-💚happy💚diwali💚
--💚happy💚diwali💚
---💚happy💚diwali💚
----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
-----💚happy💚diwali💚
----💚happy💚diwali💚
---💚happy💚diwali💚
--💚happy💚diwali💚
-💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚
💚happy💚diwali💚"""           ]

    for i in animation_ttl:
        	
        await asyncio.sleep(animation_interval)
        await event.edit(animation_chars[i % 6])
@wolfs.on(admin_cmd("diwali"))
async def _(event):
    if event.fwd_from:
        return
    animation_interval = 1
    animation_ttl = range(0,80)
    await event.edit("❤Happy Diwali Dosto❤")
    animation_chars = ["💖happy💖diwali💖","💙happy💙diwali💙","❤️happy♥️diwali❤️","💚happy💚diwali💚","💜happy💜diwali💜",]

    for i in animation_ttl:
        	
        await asyncio.sleep(animation_interval)
        await event.edit(animation_chars[i % 5])
@wolfs.on(admin_cmd("dosto"))
async def _(event):
    if event.fwd_from:
        return
    animation_interval = 1
    animation_ttl = range(0,22)
    await event.edit("❤Dosto❤")
    animation_chars = ["""💜💜                        💜💜
💜💜                        💜💜
💜💜                        💜💜
💜💜                        💜💜
💜💜💜💜💜💜💜💜💜
💜💜💜💜💜💜💜💜💜
💜💜                        💜💜
💜💜                        💜💜
💜💜                        💜💜
💜💜                        💜💜""","""ㅤㅤㅤㅤㅤ ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ
                    💙💙
                 💙💙💙
             💙💙💙💙
            💙💙 💙💙
          💙💙    💙💙
        💙💙       💙💙
     💙💙💙💙💙💙
      💙💙💙💙💙💙
   💙💙                 💙💙
  💙💙                    💙💙
💙💙                       💙💙""","""💚💚💚💚💚💚💚
💚💚💚💚💚💚💚💚
💚💚                     💚💚
💚💚                     💚💚
💚💚💚💚💚💚💚💚
💚💚💚💚💚💚💚
💚💚
💚💚
💚💚
💚💚""","""💛💛💛💛💛💛
💛💛💛💛💛💛💛
💛💛                💛💛
💛💛                💛💛
💛💛💛💛💛💛💛
💛💛💛💛💛💛
💛💛
💛💛
💛💛
💛💛""","""💜💜                    💜💜
   💜💜              💜💜
      💜💜        💜💜
         💜💜  💜💜
            💜💜💜
              💜💜
              💜💜
              💜💜
              💜💜
              💜💜""","""💖💖💖💖💖💖💖
💖💖💖💖💖💖💖💖
💖💖                      💖💖
💖💖                         💖💖
💖💖                         💖💖
💖💖                         💖💖
💖💖                         💖💖
💖💖                      💖💖
💖💖💖💖💖💖💖💖
💖💖💖💖💖💖💖""","""💝💝💝💝💝💝
💝💝💝💝💝💝
          💝💝
          💝💝
          💝💝
          💝💝
          💝💝
          💝💝
💝💝💝💝💝💝
💝💝💝💝💝💝""","""💖💖                               💖💖
💖💖                               💖💖
💖💖                               💖💖
💖💖                               💖💖
💖💖              💖            💖💖
 💖💖           💖💖          💖💖
 💖💖        💖💖💖       💖💖
  💖💖   💖💖  💖💖   💖💖
   💖💖💖💖      💖💖💖💖
    💖💖💖             💖💖💖""","""ㅤㅤㅤㅤㅤ ㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤㅤ
                    💙💙
                 💙💙💙
             💙💙💙💙
            💙💙 💙💙
          💙💙    💙💙
        💙💙       💙💙
     💙💙💙💙💙💙
      💙💙💙💙💙💙
   💙💙                 💙💙
  💙💙                    💙💙
💙💙                       💙💙""","""💘💘
💘💘
💘💘
💘💘
💘💘
💘💘
💘💘
💘💘
💘💘💘💘💘💘💘💘
💘💘💘💘💘💘💘💘""","""💝💝💝💝💝💝
💝💝💝💝💝💝
          💝💝
          💝💝
          💝💝
          💝💝
          💝💝
          💝💝
💝💝💝💝💝💝
💝💝💝💝💝💝""",]

    for i in animation_ttl:
        	
        await asyncio.sleep(animation_interval)
        await event.edit(animation_chars[i % 11])
